### ISSUE TITLE
no "mesh-cli" command in path

### ISSUE THREAD

**Issue by mclaudt** [gentics/mesh-cli#8]
After installation `npm install mesh-cli -g` I can not see `mesh-cli `in path to run `mesh-cli configure` (according to docs), but there are many `mesh-*` tools instead:

```
mesh           mesh-docker    mesh-list      mesh-unlink    
mesh-add       mesh-get       mesh-remove    mesh-update    
mesh-admin     mesh-link      mesh-sync      mesh-validate 
```

`mesh-admin configure` works well

It seems like readme is outdated.

**Comment by Jotschi** [comment]
We renamed the commands to "mesh" so you would need to use `mesh configure`

**Comment by Jotschi** [comment]
@mclaudt  I fixed the README file.
